version: '3'

services:
  # Brocan services
  bond: 
    build: ../../bond
    depends_on:
      - faktory
      - nats

  # Third-party services
  faktory:
    image: contribsys/faktory:0.5.0
    entrypoint: ./faktory -b 0.0.0.0:7419 -no-tls
    ports:
      - '7419:7419'
      - '7420:7420'
  nats:
    image: nats
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'

    