version: '3'

services:
  # Brocan services
  eternity: 
    build: ../../components/services/eternity
    depends_on:
      - mongo
      - nats

  # Third-party services
  mongo:
    image: mongo
    ports: 
      - '27017:27017'
    volumes:
      - /data/brocan:/data/db
  nats:
    image: nats
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    